name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://pablicio13:$HF@huggingface.co/spaces/pablicio13/demo

      - name: Debug Git configuration
        run: git config --list

      - name: Push to hub
        env: 
          HF: ${{ secrets.HF }}
        run: git push --force space main
